### ISSUE TITLE
Перевод блога

### ISSUE THREAD

**Issue by vvscode** [reactjs/ru.reactjs.org#273]
- [ ]  JSFiddle Integration
- [ ]  Why did we build React?
- [ ]  "Community Round-up #1"
- [ ]  "Community Round-up #2"
- [ ]  "React v0.3.3"
- [ ]  "Community Round-up #3"
- [ ]  "New in React v0.4: Autobind by Default"
- [ ]  "Community Round-up #4"
- [ ]  "New in React v0.4: Prop Validation and Default Values"
- [ ]  "React v0.4.0"
- [ ]  "Community Round-up #5"
- [ ]  "React v0.4.1"
- [ ]  "Use React and JSX in Ruby on Rails"
- [ ]  "Community Round-up #6"
- [ ]  "Use React and JSX in Python Applications"
- [ ]  "Community Round-up #7"
- [ ]  "Community Round-up #8"
- [ ]  "Community Round-up #9"
- [ ]  "React v0.5"
- [ ]  "React v0.5.1"
- [ ]  "Community Round-up #10"
- [ ]  "Community Round-up #11"
- [ ]  "React v0.5.2, v0.4.2"
- [ ]  "React v0.8"
- [ ]  "Community Round-up #12"
- [ ]  "Community Round-up #13"
- [ ]  "React Chrome Developer Tools"
- [ ]  "Community Round-up #14"
- [ ]  "Community Round-up #15"
- [ ]  "Community Round-up #16"
- [ ]  React v0.9 RC
- [ ]  React v0.9
- [ ]  "Community Round-up #17"
- [ ]  "Community Round-up #18"
- [ ]  React v0.10 RC
- [ ]  React v0.10
- [ ]  The Road to 1.0
- [ ]  "Use React and JSX in ASP.NET MVC"
- [ ]  "Flux: An Application Architecture for React"
- [ ]  "One Year of Open-Source React"
- [ ]  "Community Round-up #19"
- [ ]  React v0.11 RC
- [ ]  React v0.11
- [ ]  React v0.11.1
- [ ]  "Community Round-up #20"
- [ ]  "Flux: Actions and the Dispatcher"
- [ ]  "Community Round-up #21"
- [ ]  "Introducing the JSX Specification"
- [ ]  "Community Round-up #22"
- [ ]  React v0.11.2
- [ ]  "Testing Flux Applications"
- [ ]  "Introducing React Elements"
- [ ]  "React v0.12 RC"
- [ ]  "Community Round-up #23"
- [ ]  React.js Conf
- [ ]  React v0.12
- [ ]  React.js Conf Updates
- [ ]  "Community Round-up #24"
- [ ]  React v0.12.2
- [ ]  React.js Conf Diversity Scholarship
- [ ]  React v0.13.0 Beta 1
- [ ]  React.js Conf Round-up 2015
- [ ]  "Introducing Relay and GraphQL"
- [ ]  "React v0.13 RC"
- [ ]  "Streamlining React Elements"
- [ ]  "React v0.13 RC2"
- [ ]  "Community Round-up #25"
- [ ]  "React v0.13"
- [ ]  "React v0.13.1"
- [ ]  "Building The Facebook News Feed With Relay"
- [ ]  "Introducing React Native"
- [ ]  "Community Round-up #26"
- [ ]  "React Native v0.4"
- [ ]  "React v0.13.2"
- [ ]  "GraphQL Introduction"
- [ ]  "React v0.13.3"
- [ ]  "React Native Release Process"
- [ ]  "Deprecating JSTransform and react-tools"
- [ ]  React v0.14 Beta 1
- [ ]  "New React Devtools Beta"
- [ ]  "Relay Technical Preview"
- [ ]  "ReactEurope Round-up"
- [ ]  "New React Developer Tools"
- [ ]  "React v0.14 Release Candidate"
- [ ]  "Community Round-up #27 – Relay Edition"
- [ ]  "ReactDOM.render and the Top Level React API"
- [ ]  "React v0.14"
- [ ]  "Reactiflux is moving to Discord"
- [ ]  "React v0.14.1"
- [ ]  "React v0.14.2"
- [ ]  "React v0.14.3"
- [ ]  React.js Conf 2016 Diversity Scholarship
- [ ]  "isMounted is an Antipattern"
- [ ]  "React Components, Elements, and Instances"
- [ ]  "React v0.14.4"
- [ ]  "(A => B) !=> (B => A)"
- [ ]  "Discontinuing IE 8 Support in React DOM"
- [ ]  "New Versioning Scheme"
- [ ]  "React v15.0 Release Candidate"
- [ ]  "React v15.0 Release Candidate 2"
- [ ]  "React v0.14.8"
- [ ]  "React v15.0"
- [ ]  "React v15.0.1"
- [ ]  "Introducing React's Error Code System"
- [ ]  "Mixins Considered Harmful"
- [ ]  "Create Apps with No Configuration"
- [ ]  "Relay: State of the State"
- [ ]  "Our First 50,000 Stars"
- [ ]  "React v15.4.0"
- [ ]  "React v15.5.0"
- [ ]  "What's New in Create React App"
- [ ]  "React v15.6.0"
- [ ]  "Error Handling in React 16"
- [ ]  "DOM Attributes in React 16"
- [ ]  'title',
- [ ]  "React v15.6.2"
- [ ]  "React v16.0"
- [ ]  "React v16.2.0: Improved Support for Fragments"
- [ ]  "Introducing the React RFC Process"
- [ ]  "Behind the Scenes: Improving the Repository Infrastructure"
- [ ]  "Sneak Peek: Beyond React 16"
- [ ]  Update on Async Rendering
- [ ]  "React v16.3.0: New lifecycles and context API"
- [ ]  "React v16.4.0: Pointer Events"
- [ ]  "You Probably Don't Need Derived State"
- [ ]  "React v16.4.2: Server-side vulnerability fix"
- [ ]  "Introducing the React Profiler"
- [ ]  "Create React App 2.0: Babel 7, Sass, and More"
- [ ]  "React v16.6.0: lazy, memo and contextType"
- [ ]  "React Conf recap: Hooks, Suspense, and Concurrent Rendering"
- [ ]  "React 16.x Roadmap"
- [ ]  "React v16.7: No, This Is Not the One With Hooks"
- [ ]  "React v16.8: The One With Hooks"
- [ ]  "Is React Translated Yet? ¡Sí! Sim! はい！"

**Comment by another-guy** [comment]
@vvscode мне кажется, для сообщества более важны актуальные посты, чем исторические. Поэтому я отсортировал посты в обратном (обратном хронологическом?) порядке, и по ним можно идти сверху вниз.

**Comment by vvscode** [comment]
`"React v16.8: The One With Hooks"` готов взять

**Comment by gcor** [comment]
Где-то я видел, но не могу найти, советовали переводить статьи не в хронологическом порядке, а брать вначале те, которые дополняют документацию. 

Например, я бы назвал самой приоритетной статью https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html

**Comment by another-guy** [comment]
@gcor тоже вариант, но тогда неплохо бы всё-таки найти курируемый список приоритета переводов.

**Comment by arsts** [comment]
"React v16.7: No, This Is Not the One With Hooks"  готов взять

**Comment by gcor** [comment]
@lex111, @ntishkevich, @another-guy 
Кажется идея с переводом блога не очень пошла. Большой список скорее демотивирует. 

Предлагаю сократить текущий список и закрыть задачу или создать несколько задач для важных страниц из блога с тегами good first issue и help wanted. По аналогии с репозиторием португальского перевода https://github.com/reactjs/pt-BR.reactjs.org/issues

На мой взгляд подходящие страницы:
1. https://ru.reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html
2. https://ru.reactjs.org/blog/2019/02/06/react-v16.8.0.html
3. https://ru.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html

**Comment by ntishkevich** [comment]
Тогда я предложил бы вариант с тем, чтобы выделить из текущего списка некоторые статьи из блога как отдельные задачи. Вот примерный список тех статей,которые я бы выделил в перевод первым делом.
-  "Is React Translated Yet? ¡Sí! Sim! はい！"
-  "React v16.8: The One With Hooks" 
-  "React v16.7: No, This Is Not the One With Hooks"
-  "React 16.x Roadmap"
-  "React Conf recap: Hooks, Suspense, and Concurrent Rendering"
-  "React v16.6.0: lazy, memo and contextType"
-  "Create React App 2.0: Babel 7, Sass, and More"
-  "Introducing the React Profiler"
-  "React v16.4.2: Server-side vulnerability fix"
-  "You Probably Don't Need Derived State"
-  "React v16.4.0: Pointer Events"
-  "React v16.3.0: New lifecycles and context API"
-  Update on Async Rendering
-  "Sneak Peek: Beyond React 16"
-  "Behind the Scenes: Improving the Repository Infrastructure"
-  "Introducing the React RFC Process"
-  "React v16.2.0: Improved Support for Fragments"

**Comment by lyskos97** [comment]
Хочу взять на перевод "Is React Translated Yet? ¡Sí! Sim! はい！"

**Comment by lex111** [comment]
Отлично! :+1:

**Comment by lyskos97** [comment]
Могу зацепить "React Conf recap: Hooks, Suspense, and Concurrent Rendering" на перевод?

**Comment by ntishkevich** [comment]
> Могу зацепить "React Conf recap: Hooks, Suspense, and Concurrent Rendering" на перевод?

Это здорово!

**Comment by lyskos97** [comment]
Хочу перевести "React v16.6.0: lazy, memo and contextType"

**Comment by karpa4o4** [comment]
Готов взять `Create React App 2.0: Babel 7, Sass, and More`.

**Comment by hodovani** [comment]
Возьму `JSFiddle Integration`.

**Comment by peakercope** [comment]
Готов взять "Introducing the React Profiler"

**Comment by Aki120900** [comment]
Здравствуйте, @lex111, @ntishkevich, @another-guy!
Хотела бы взяться за перевод статьи "Introducing the React Profiler".
Пожалуйста, дайте знать, если она уже занята или есть какие-либо рекомендации.
