### ISSUE TITLE
Перевод раздела Concurrent Mode

### ISSUE THREAD

**Issue by gcor** [reactjs/ru.reactjs.org#422]
- [x] Introducing Concurrent Mode @gcor #453
- [x] Suspense for Data Fetching @shdq #446 
- [x] Concurrent UI Patterns @SmolinPavel #472 (файл был удален в английской документации)
- [x] Adopting Concurrent Mode @AlLevykin #430 
- [x] Concurrent Mode API Reference @AlLevykin #463 

**Полезные материалы:**
- [Текущее соглашение о переводе](https://github.com/reactjs/ru.reactjs.org/blob/master/TRANSLATION.md)
- [Обсуждение перевода термина Concurrent Mode](https://github.com/reactjs/ru.reactjs.org/issues/423)
- [Suspense переводится как *задержка*](https://github.com/reactjs/ru.reactjs.org/pull/70).

## Как помочь с переводом
Вы можете перевести страницу из документации! Это делается в три шага:

1. Проверьте, что её никто не застолбил в чеклисте или комментариях под ним
2. Напишите, какую страницу вы ходите перевести. Пожалуйста, не берите больше одной страницы за раз.
3. Когда страница готова, отредактируйте ваш комментарий, чтобы добавить номер пулреквеста.

**Comment by AlLevykin** [comment]
Могу взять раздел Adopting Concurrent Mode (concurrent-mode-adoption.md).

**Comment by shdq** [comment]
Привет, переведу Suspense for Data Fetching.

**Comment by AlLevykin** [comment]
Могу взять раздел Concurrent Mode API Reference (concurrent-mode-reference.md).

**Comment by SmolinPavel** [comment]
Готов взять Concurrent UI Patterns

**Comment by lex111** [comment]
@SmolinPavel как дела с переводом?

**Comment by SmolinPavel** [comment]
@lex111 пока готов на 30%, постараюсь ускориться и на выходных сделаю PR

**Comment by lex111** [comment]
@SmolinPavel может нужна помочь с переводом? Можно создать черновик перевода, чтобы ускорить процесс.

**Comment by SmolinPavel** [comment]
@lex111 будет нужна помощь, создал черновик https://github.com/reactjs/ru.reactjs.org/pull/472

**Comment by kostia-lev** [comment]
я не понимаю почему Concurrent mode перевели как Конкурентный режим? 
![image](https://user-images.githubusercontent.com/1144764/163727872-a2933f42-7479-4278-8180-9847d010e6ef.png)

**Comment by shdq** [comment]
@kostia-lev было обсуждение термина, загляни в issue https://github.com/reactjs/ru.reactjs.org/issues/423

**Comment by ntishkevich** [comment]
все элементы из списка переведены. Спасибо всем за вашу помощь в переводе. Закрываю ишью.
